// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

// SwaggerInfo holds exported Swagger Definition
var SwaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

func init() {
	SwaggerInfo.Version = "0.0.1"
	SwaggerInfo.Title = "SocialNetwork API"
	SwaggerInfo.Description = "API for SocialNetwork"
	SwaggerInfo.BasePath = "/api/v1"
}
